### ISSUE TITLE
Something went wrong with Extension for Rollout

### ISSUE THREAD

**Issue by juanvasquezreyes** [argoproj-labs/rollout-extension#2]
I'm using argocd version: v2.1.6

Getting the following error when trying to see the rollout details "Something went wrong with Extension for Rollout"
![image](https://user-images.githubusercontent.com/20667703/140103187-7b37bca3-7b87-450c-bc78-370f5304ef54.png)

in the rollout service it looks ok, but not in the extension
![image](https://user-images.githubusercontent.com/20667703/140103355-79c156ac-5b24-4bdf-ad0c-da5dc02c40b1.png)

In the extension container I dont see any error
```
I1103 16:28:41.790412       1 request.go:665] Waited for 1.029562587s due to client-side throttling, not priority and fairness, request: GET:https://10.1.0.1:443/apis/node.k8s.io/v1?timeout=32s
2021-11-03T16:28:42.193Z	INFO	setup	starting manager
2021-11-03T16:28:42.194Z	INFO	controller.argocdextension	Starting EventSource	{"reconciler group": "argoproj.io", "reconciler kind": "ArgoCDExtension", "source": "kind source: /, Kind="}
2021-11-03T16:28:42.194Z	INFO	controller.argocdextension	Starting Controller	{"reconciler group": "argoproj.io", "reconciler kind": "ArgoCDExtension"}
2021-11-03T16:28:42.295Z	INFO	controller.argocdextension	Starting workers	{"reconciler group": "argoproj.io", "reconciler kind": "ArgoCDExtension", "worker count": 1}
2021-11-03T16:28:42.295Z	INFO	controller.argocdextension	Sources has not been downloaded yet, redownloading...	{"reconciler group": "argoproj.io", "reconciler kind": "ArgoCDExtension", "name": "argo-rollouts", "namespace": "gitops"}
2021-11-03T16:28:42.896Z	INFO	controller.argocdextension	Successfully downloaded all sources.	{"reconciler group": "argoproj.io", "reconciler kind": "ArgoCDExtension", "name": "argo-rollouts", "namespace": "gitops"}
2021-11-03T16:28:42.915Z	INFO	controller.argocdextension	Sources already downloaded.	{"reconciler group": "argoproj.io", "reconciler kind": "ArgoCDExtension", "name": "argo-rollouts", "namespace": "gitops"}
```

am I missing something?

**Comment by mmosttler** [comment]
I am seeing this same behavior with the latest versions of argocd (2.2.3) and rollouts (1.1.1)

**Comment by diegoluisi** [comment]
Same error

**Comment by zivaja** [comment]
Same error
Argo CD: v2.2.5+8f981cc
Argo Rollout: v1.1.0+ff3471a

**Comment by AnthonyWC** [comment]
Seeing this error itself on all rollout; tried to delete/re-create ArgoCDExtension and upgraded argo-rollout (maybe newer version of rollout broke it?):
```
{
    "Version": "v2.3.3+07ac038",
    "BuildDate": "2022-03-30T00:06:18Z",
    "GitCommit": "07ac038a8f97a93b401e824550f0505400a8c84e",
    "GitTreeState": "clean",
    "GoVersion": "go1.17.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.0+gd141386",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}

argo-rollouts:v1.2.0
```

**Comment by DZhuribeda** [comment]
Hey, 
I see the same error. I found an error in the console 
```
TypeError: Cannot read properties of undefined (reading 'length')
    at extensions.js:294:59224
    at Me (extensions.js:294:59384)
    at qo (main.c7ea22e999b3805bc676.js:404:57924)
    at ga (main.c7ea22e999b3805bc676.js:404:104163)
    at cl (main.c7ea22e999b3805bc676.js:404:96711)
    at al (main.c7ea22e999b3805bc676.js:404:96636)
    at Qa (main.c7ea22e999b3805bc676.js:404:93666)
    at main.c7ea22e999b3805bc676.js:404:45314
    at t.unstable_runWithPriority (main.c7ea22e999b3805bc676.js:412:3844)
    at zr (main.c7ea22e999b3805bc676.js:404:45023)
```

I assume that's related to referencing deployment instead of using rollout directly.

**Comment by aywrite** [comment]
I started seeing this error as well - once I switch from a full rollout object to a rollout object which references a deployment. 

```
main.be2426d1b32bf6fca51b.js:2 TypeError: Cannot read properties of undefined (reading 'length')
    at extensions.js:294:59224
    at Me (extensions.js:294:59384)
    at Jo (main.be2426d1b32bf6fca51b.js:2:793103)
    at ya (main.be2426d1b32bf6fca51b.js:2:839008)
    at pl (main.be2426d1b32bf6fca51b.js:2:831784)
    at dl (main.be2426d1b32bf6fca51b.js:2:831709)
    at il (main.be2426d1b32bf6fca51b.js:2:828739)
    at main.be2426d1b32bf6fca51b.js:2:780518
    at t.unstable_runWithPriority (main.be2426d1b32bf6fca51b.js:2:855566)
    at Yr (main.be2426d1b32bf6fca51b.js:2:780227)
```

```
{
    "Version": "v2.4.2+c6d0c8b",
    "BuildDate": "2022-06-21T20:42:05Z",
    "GitCommit": "c6d0c8baaa291cd68465acd7ad6bef58b2b6f942",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.1+g5cb9af4",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}
```

**Comment by juanvasquezreyes** [comment]
I tested a little bit more and I think the problem is in the rollout type, if you use a regular canary it work just fine, but if you use workloadref it doesnt work

**Comment by byangtri** [comment]
I am also encountering the same issue in our environment when using `workloadRef` to our Deployments

**Comment by httin** [comment]
All of my applications using `workloadRef` are encountering this issue, while applications using Rollout `template` work just fine.

**Comment by Va1** [comment]
apparently, this can also happen when there are leftover ReplicaSets left in the same App, which are not managed by the Rollout. removing those manually or pruning automatically helps.
