### ISSUE TITLE
Something went wrong with Extension for Rollout (v0.3.2)

### ISSUE THREAD

**Issue by maxtacu** [argoproj-labs/rollout-extension#59]
After upgrade to latest v0.3.2 the extension is not working and we get this message in the ArgoCD UI
![image](https://github.com/argoproj-labs/rollout-extension/assets/17516391/8d6e5664-b503-42e0-a35f-b15d17172614)
There are no errors in in the argocd-server. 
In developer console I get this error:
```
main.33289ad3bf773ac1ef51.js:2 Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at t.findDOMNode (extensions.js:331:117265)
    at I (extensions.js:9:77442)
    at p (extensions.js:9:78157)
    at extensions.js:9:78816
    at cs (main.33289ad3bf773ac1ef51.js:2:833615)
    at Dl (main.33289ad3bf773ac1ef51.js:2:852520)
    at t.unstable_runWithPriority (main.33289ad3bf773ac1ef51.js:2:870971)
    at qo (main.33289ad3bf773ac1ef51.js:2:795478)
    at Ll (main.33289ad3bf773ac1ef51.js:2:852272)
    at hl (main.33289ad3bf773ac1ef51.js:2:844031)
```

**Comment by Marvin9** [comment]
I suspect this coming from argo rollouts UI as this repo depends on rollouts, and this error is possibly coming from rollouts UI.

I have added fix there. When it is merged, I will update this repo to point updated rollout UI. Which will most probably (not completely sure) fix this issue.

**Comment by Marvin9** [comment]
Can you please try v0.3.4?

**Comment by maxtacu** [comment]
Forgot to mention. Works fine on the version mentioned above. Closing the issue
