### ISSUE TITLE
Cannot read properties of undefined (reading 'resources')

### ISSUE THREAD

**Issue by endriu0** [argoproj-labs/rollout-extension#78]
Getting this recently on few of our argocd deployments. Seems to be related to the extension hence posting here : 

```
Something went wrong!

Consider submitting an issue [here](https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md).


Stacktrace:

TypeError: Cannot read properties of undefined (reading 'resources')
    at https://argo-hostname/main.08bea4d9f3b3774bfab7.js:2:1560868
    at uc.extensions.getResourceTabs (https://argo-hostname/main.08bea4d9f3b3774bfab7.js:2:1560963)
    at https://argo-hostname/main.08bea4d9f3b3774bfab7.js:2:1821414
    at ok (https://argo-hostname/main.08bea4d9f3b3774bfab7.js:2:1821615)
    at Za (https://argo-hostname/main.08bea4d9f3b3774bfab7.js:2:756839)
    at Bi (https://argo-hostname/main.08bea4d9f3b3774bfab7.js:2:765686)
    at Es (https://argo-hostname/main.08bea4d9f3b3774bfab7.js:2:804104)
    at kl (https://argo-hostname/main.08bea4d9f3b3774bfab7.js:2:795645)
    at xl (https://argo-hostname/main.08bea4d9f3b3774bfab7.js:2:795570)
    at hl (https://argo-hostname/main.08bea4d9f3b3774bfab7.js:2:792593)
  ```
  
  Usually I can just refresh page and the error will go away but sometimes needs 2 or 3 refreshes for the error to go out.  Happens only when trying to actually click into resource. Seems to mainly appear on 2.11.0 argocd.
  
  Argocd version json : 
  
  ```json
  {
    "Version": "v2.11.0+d3f33c0",
    "BuildDate": "2024-05-07T16:01:41Z",
    "GitCommit": "d3f33c00197e7f1d16f2a73ce1aeced464b07175",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.9",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.3+gf03cc04",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

Rollouts Extension version : `v0.3.5`
Rollouts extension installed via helm values : 
```
          extensions:
            enabled: true
            extensionList:
              - name: rollout-extension
                env:
                  - name: EXTENSION_URL
                    value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.5/extension.tar

**Comment by endriu0** [comment]
Looks like it's fixed with newer argocd / extension. Closing
